# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS adios2::adios2sys adios2::adios2sys_private adios2::perfstubs adios2::pybind11 adios2::nlohmann_json_wrapper adios2::core adios2::core_mpi adios2::core_mpi_c adios2::core_cuda adios2::EncryptionOperator)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target adios2::adios2sys
add_library(adios2::adios2sys INTERFACE IMPORTED)

set_target_properties(adios2::adios2sys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/thirdparty/KWSys/adios2sys"
  INTERFACE_LINK_LIBRARIES "dl"
)

# Create imported target adios2::adios2sys_private
add_library(adios2::adios2sys_private INTERFACE IMPORTED)

set_target_properties(adios2::adios2sys_private PROPERTIES
  INTERFACE_LINK_LIBRARIES "adios2::adios2sys"
  INTERFACE_SOURCES "\$<TARGET_OBJECTS:adios2sys_objects>"
)

# Create imported target adios2::perfstubs
add_library(adios2::perfstubs SHARED IMPORTED)

set_target_properties(adios2::perfstubs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/jlx/Projects/CAESAR_ALL/ADIOS2/thirdparty/perfstubs/perfstubs;/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/thirdparty/perfstubs/perfstubs"
  INTERFACE_LINK_LIBRARIES "dl;m"
)

# Create imported target adios2::pybind11
add_library(adios2::pybind11 INTERFACE IMPORTED)

set_target_properties(adios2::pybind11 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/jlx/Projects/CAESAR_ALL/ADIOS2/thirdparty/pybind11/pybind11/include"
)

# Create imported target adios2::nlohmann_json_wrapper
add_library(adios2::nlohmann_json_wrapper INTERFACE IMPORTED)

set_target_properties(adios2::nlohmann_json_wrapper PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<AND:\$<COMPILE_LANGUAGE:CXX>,\$<CXX_COMPILER_ID:Intel>>:-Wno-all;-Wno-error>"
  INTERFACE_INCLUDE_DIRECTORIES "/home/jlx/Projects/CAESAR_ALL/ADIOS2/thirdparty/nlohmann_json/nlohmann_json_wrapper;/home/jlx/Projects/CAESAR_ALL/ADIOS2/thirdparty/nlohmann_json/nlohmann_json_wrapper/single_include"
  INTERFACE_SOURCES "/home/jlx/Projects/CAESAR_ALL/ADIOS2/thirdparty/nlohmann_json/nlohmann_json_wrapper/nlohmann_json.hpp;/home/jlx/Projects/CAESAR_ALL/ADIOS2/thirdparty/nlohmann_json/nlohmann_json_wrapper/single_include/nlohmann/json.hpp"
)

# Create imported target adios2::core
add_library(adios2::core SHARED IMPORTED)

set_target_properties(adios2::core PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_auto_type;cxx_nullptr"
  INTERFACE_INCLUDE_DIRECTORIES "/home/jlx/Projects/CAESAR_ALL/ADIOS2/source;/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/source"
)

# Create imported target adios2::core_mpi
add_library(adios2::core_mpi SHARED IMPORTED)

set_target_properties(adios2::core_mpi PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ADIOS2_USE_MPI"
  INTERFACE_LINK_LIBRARIES "adios2::core;MPI::MPI_CXX"
)

# Create imported target adios2::core_mpi_c
add_library(adios2::core_mpi_c INTERFACE IMPORTED)

set_target_properties(adios2::core_mpi_c PROPERTIES
  INTERFACE_LINK_LIBRARIES "adios2::core_mpi;MPI::MPI_C"
)

# Create imported target adios2::core_cuda
add_library(adios2::core_cuda SHARED IMPORTED)

# Create imported target adios2::EncryptionOperator
add_library(adios2::EncryptionOperator MODULE IMPORTED)

set_target_properties(adios2::EncryptionOperator PROPERTIES
  INTERFACE_LINK_LIBRARIES "adios2::core;sodium"
)

# Import target "adios2::perfstubs" for configuration "Release"
set_property(TARGET adios2::perfstubs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(adios2::perfstubs PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/lib/libadios2_perfstubs.so.2.11.0"
  IMPORTED_SONAME_RELEASE "libadios2_perfstubs.so.2.11"
  )

# Import target "adios2::core" for configuration "Release"
set_property(TARGET adios2::core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(adios2::core PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "adios2::core_cuda;caesar::caesar_lib"
  IMPORTED_LOCATION_RELEASE "/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/lib/libadios2_core.so.2.11.0"
  IMPORTED_SONAME_RELEASE "libadios2_core.so.2.11"
  )

# Import target "adios2::core_mpi" for configuration "Release"
set_property(TARGET adios2::core_mpi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(adios2::core_mpi PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/lib/libadios2_core_mpi.so.2.11.0"
  IMPORTED_SONAME_RELEASE "libadios2_core_mpi.so.2.11"
  )

# Import target "adios2::core_cuda" for configuration "Release"
set_property(TARGET adios2::core_cuda APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(adios2::core_cuda PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/lib/libadios2_core_cuda.so"
  IMPORTED_SONAME_RELEASE "libadios2_core_cuda.so"
  )

# Import target "adios2::EncryptionOperator" for configuration "Release"
set_property(TARGET adios2::EncryptionOperator APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(adios2::EncryptionOperator PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/jlx/Projects/CAESAR_ALL/ADIOS2/adios2-build/lib/libEncryptionOperator.so"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
