#define ADIOS_INFO_VER_GIT       ""
#define ADIOS_INFO_COMPILER_ID   "GNU"
#define ADIOS_INFO_COMPILER_VER  "13.3.0"
#define ADIOS_INFO_COMPILER_WRAP ""
#define ADIOS_INFO_SYSTEM        "Linux-6.8.0-83-generic"
#define ADIOS_INFO_ARCH          "x86_64"
