name: adios2-python-docs

channels:
  - conda-forge

dependencies:
  - python ==3.12
  - breathe
  - cmake
  - docutils
  - libpython-static
  - ninja
  - numpy
  - pip
  - sphinx
  - pip:
    - blockdiag
    - sphinxcontrib-blockdiag
    - sphinx_rtd_theme
